# Generated by Django 2.1.2 on 2019-12-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuidingAccessRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('floors', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='buidingaccessrole',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takelog.Building'),
        ),
    ]
